"""create_datasource_context_bridge_table

Revision ID: 222c1b030b19
Revises: f41af0c76a60
Create Date: 2023-07-03 00:27:19.076145

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '222c1b030b19'
down_revision = 'f41af0c76a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasource_context',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('datasource_id', sa.Integer(), nullable=False),
        sa.Column('context_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('datasource_id', 'context_id', name='relationship')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasource_context')
    # ### end Alembic commands ###
