"""create_datasource_context_map_table

Revision ID: 3611ccaad282
Revises: 222c1b030b19
Create Date: 2023-07-03 00:31:51.163094

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3611ccaad282'
down_revision = 'f41af0c76a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasource_context_map',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasource_field', sa.String(), nullable=False),
    sa.Column('context_field', sa.String(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasource_context_map')
    # ### end Alembic commands ###
