"""create_datasource_types

Revision ID: 4d86aff1288f
Revises: 25a5bc8a07e2
Create Date: 2023-07-02 19:52:28.576514

"""
from alembic import op
import sqlalchemy as sa
import datetime

# revision identifiers, used by Alembic.
revision = '4d86aff1288f'
down_revision = '25a5bc8a07e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    datasource_types_table = op.create_table('datasource_types',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(
        datasource_types_table,
        [
            {
                "name": "CSV",
                "description": "CSV File",
                "created_at": datetime.datetime.now()
            },
            {
                "name": "DB",
                "description": "Database",
                "created_at": datetime.datetime.now()
            }
        ],
    )
    op.add_column('datasources', sa.Column('type_id', sa.Integer(), nullable=True, server_default='1'))
    op.alter_column('datasources', 'type_id', nullable=False, server_default=None)
    op.create_foreign_key(None, 'datasources', 'datasource_types', ['type_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('datasources_type_id_fkey', 'datasources', type_='foreignkey')
    op.drop_column('datasources', 'type_id')
    op.drop_table('datasource_types')
    # ### end Alembic commands ###
