"""create_database_table

Revision ID: f41af0c76a60
Revises: 4d86aff1288f
Create Date: 2023-07-03 00:24:28.080027

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f41af0c76a60'
down_revision = '4d86aff1288f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databases',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('user', sa.String(), nullable=True),
        sa.Column('password', sa.String(), nullable=True),
        sa.Column('query', sa.String(), nullable=False),
        sa.Column('driver_id', sa.Integer(), nullable=False),
        sa.Column('datasource_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['driver_id'], ['jdbc_drivers.id'], onupdate='CASCADE', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('databases')
    # ### end Alembic commands ###
