"""updating_datasource_column_constraints

Revision ID: f4b0665a8237
Revises: 3611ccaad282
Create Date: 2023-07-03 03:33:11.549037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4b0665a8237'
down_revision = '3611ccaad282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasource_context', 'context_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('datasource_context', 'datasource_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('datasources', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasources', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('datasource_context', 'datasource_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('datasource_context', 'context_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
